// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0c3DD56S2ndRDxxtphofL8SKUbcZU_1o',
    appId: '1:788979794604:web:2c37bea513614743ac9509',
    messagingSenderId: '788979794604',
    projectId: 'jobsearch-51159',
    authDomain: 'jobsearch-51159.firebaseapp.com',
    storageBucket: 'jobsearch-51159.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYLFSv4RkP2JOiXNHA8OJjhtbByPcZ8Jg',
    appId: '1:788979794604:android:af9c26f4b6a81e03ac9509',
    messagingSenderId: '788979794604',
    projectId: 'jobsearch-51159',
    storageBucket: 'jobsearch-51159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQqphMNMj3gnOD9tigAhmnQkEnFPtfu8Q',
    appId: '1:788979794604:ios:ee7b13e36f79199dac9509',
    messagingSenderId: '788979794604',
    projectId: 'jobsearch-51159',
    storageBucket: 'jobsearch-51159.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0c3DD56S2ndRDxxtphofL8SKUbcZU_1o',
    appId: '1:788979794604:web:c78a5bac5692127cac9509',
    messagingSenderId: '788979794604',
    projectId: 'jobsearch-51159',
    authDomain: 'jobsearch-51159.firebaseapp.com',
    storageBucket: 'jobsearch-51159.firebasestorage.app',
  );
}
